### PR TITLE
unduplicate proxy.config doc and samples

### LINKED ISSUE #49: reorganize example serverUrls in doc
link to one authoritative document on <serverUrl> tags with examples in main readme and link from indivdual project readmes.

### PR DESCRIPTION
**Pull request by jgravois**
resolves #49.

### CODE REVIEW

**Comment by bsvensson** [comment]
Thanks @jgravois for starting this. I made some minor changes to this PR, please review.

Q. What should we do when there is something specific to some proxies?
Do we keep it in the individual files or do we add it to the main file with a note?

For example, with this pull request the logLevel property got removed for Java.  It wasn't doc'd (but implemented) for DotNet and PHP. The valid values differ completely between the different proxies:

Java: 
    * **logLevel="SEVERE"** : Sets the level of logging to be used.  Defaults to `SEVERE`. Possible values are SEVERE, WARNING, INFO, CONFIG, FINE, FINER and FINEST.

.Net - see #234/#233: 
    * **logLevel="Error"** : Sets the level of logging to be used.  Defaults to `Error`. Possible values are "Off","Error","Warning","Info","Verbose" or 0-4.

PHP:
    * **logLevel="3"** : Sets the level of logging to be used.  Defaults to `3` (no logging). Possible values are "0" (log to logfile),"1" (log to browser console), "2" (log to logfile as well as to browser console) and "3" (no logging).

**Comment by jgravois** [comment]
> I made some minor changes to this PR, please review.

* markdown page links are not case sensitive, but your changes don't do any harm
* i like the extra links you added.

i definitely feel like logging is the territory in the proxies with the greatest inconsistencies.  i can't be bothered to do it myself, but my recommendation is that we write up a seperate section on logging specifically (including placement of actual logging files etc.) and see whether its a better fit in the main README or in each individual proxy README.

**Comment by bsvensson** [comment]
> * markdown page links are not case sensitive, but your changes don't do any harm

@jgravois - FYI, when reading the markdown pages on GitHub, the URL's are case-sensitive - for example https://github.com/Esri/resource-proxy/blob/patch-49/README.md#proxy-configuration-settings works, but https://github.com/Esri/resource-proxy/blob/patch-49/README.md#Proxy-Configuration-Settings is not.

**Comment by jgravois** [comment]
:+1: good to know.

**Comment by jgravois** [comment]
rebased and force pushed to resolve merge conflict.

**Comment by bsvensson** [comment]
@jgravois - I made two more commits. Please review.

Otherwise, I think this PR is ready to merge.

Side note: In addition to **logLevel**, we should also doc **logFile** in more details - and their differences between the proxies.  I'll create another issue for that

**Comment by jgravois** [comment]
I'm out of the office till next week so have at it @Esri/resource-proxy

**Comment by jgravois** [comment]
lgtm!

**Pull request merged**
