### PR TITLE
Semantic versioning and Unreleased section in change log

### PR DESCRIPTION
**Pull request by bsvensson**
@jgravois - please review

### CODE REVIEW

**Comment by bsvensson** [comment]
#270

**Comment by jgravois** [comment]
thanks for this @bsvensson! some nitpicky feedback (in the interest of following the example [here](http://keepachangelog.com/) to a T).
1.
```
# Change log
## Version Number - Date
### Changed/Fixed/Added
- line items
```
2.
~~release date on seperate line~~

adhering to this convention completely would allow us to utilize commandline tools like [gh-release](https://www.npmjs.com/package/gh-release) to automate tagging.

let me know if any of that doesn't make sense.

**Comment by bsvensson** [comment]
I added the grouping of changes into Added/Fixed/Security.  See cc2c4d1.

About the ## line, there are several issues/discussions in the [keep-a-changelog repo](https://github.com/olivierlacan/keep-a-changelog/issues) about alternatives/changes. This doesn't seem stable yet... I'm OK moving the date to the line with the version number but not sure which format to go with (in order of my personal preference:
```
Version 1.1.0 - YYYY-MM-DD
1.1.0 - YYYY-MM-DD
Version 1.1.0 *(YYYY-MM-DD)*  // the italic looks nice when displayed as markdown
1.1.0 *(YYYY-MM-DD)*
Version 1.1.0 / YYYY-MM-DD
1.1.0 / YYYY-MM-DD
[1.1.0](1.1.0) - YYYY-MM-DD
[1.1.0] - YYYY-MM-DD
1.1.0
```
All of these are from different issues/discussions on that repo.  Which are [gh-release](https://www.npmjs.com/package/gh-release) friendly?

**Comment by jgravois** [comment]
i like `1.1.0 - yyyy-mm-dd`.  

thats what we use in [koop](https://github.com/koopjs/koop/blob/master/CHANGELOG.md) so i know its `gh-release` friendly.

**Comment by bsvensson** [comment]
@jgravois - actually in koop you use `## [2.6.0] - 2015-07-30` which GitHub.com automagically turns into a link:
`<a href="https://github.com/Esri/koop/compare/v2.5.3...v2.6.0">2.6.0</a>` when displayed on github. Very nice. Not sure exactly how that works, but sounds like it's worth a try.

Even `## [Unreleased][unreleased]` does some magic to create a useful link on https://github.com/olivierlacan/keep-a-changelog/blob/gh-pages/CHANGELOG.md#unreleased

@jgravois - I made an update to change to "##" headers. Please review and merge (if good enought).

**Comment by ngoldman** [comment]
:sparkles: I'm dropping in to say a thing! :sparkles: 

@bsvensson There is no magic! If you look at the bottom of those files, the links are defined there.

https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/gh-pages/CHANGELOG.md

It's just an alternate way of defining link references in markdown.

```
## [2.6.0] - 2015-07-30
### Fixed
* Parsing the logpath in `lib/Logger` needed to use slice instead of splice
* Try to use latest WKID or WKID, whichever is available in esri-proj-codes

...

[2.6.0]: https://github.com/Esri/koop/compare/v2.5.3...v2.6.0
```

:rocket: that's all! goodbye :rocket:

**Comment by bsvensson** [comment]
Thanks @ngoldman that makes sense now.

**Comment by ngoldman** [comment]
The advantage of those links is that we get nice commit diffs in our change logs. They're definitely not a necessity but a nice bonus if a project maintainer is willing to add them in. I've been trying to add them to all koop-related repos and personal projects when I get the chance.

**Comment by jgravois** [comment]
thank you both!

**Comment by bsvensson** [comment]
FYI: I'll make a minor (separate) update soon with the footnotes.

**Comment by ngoldman** [comment]
Thanks @bsvensson! @jgravois is next to me in Portland and accidentally merged a little prematurely.

**Pull request merged**
