### PR TITLE
Java: split query string and uri for POST request

### LINKED ISSUE #177: Support for ArcGIS Server 10.3
DotNet and Java Proxy failed to get token to ArcGIS Server 10.3 with this error in the log file, 

```
WARNING: Token cannot be obtained: {"error":{"code":405,"message":"Method not supported","details":"Generate Token request should not contain username and password in the query string."}}
```

This is because ArcGIS Server 10.3 only supports POST request for token request and does not support username and password in query string , see this doc, http://server.arcgis.com/en/server/latest/administer/windows/acquiring-arcgis-tokens.htm

### PR DESCRIPTION
**Pull request by esoekianto**
updated version of #178, due to merge conflict. 

split the query string from uri for POST request, to support token request for server 10.3

should fix #177

### CODE REVIEW

**Comment by cheetah90** [comment]
Cannot verify this. What I've done:
1. Add the line of code in your commit on the top of current master branch
2. Add the following code snippet in proxy.config
```		<serverUrl 
		url="http://serwin:6080/arcgis/rest/services/SampleWorldCities/MapServer" 
		username="arcgis" 
		password="arcgis" 
		rateLimit="500" 		
		matchAll="true"/>```

3. restart tomcat and try accessing ```http://alin:8080/Java/proxy.jsp?http://serwin:6080/arcgis/rest/services/SampleWorldCities/MapServer``` but failed

**Comment by cheetah90** [comment]
cc: @bsvensson @esoekianto

**Comment by esoekianto** [comment]
worked with @cheetah90 

regardless of this PR, the local JSP proxy in the test machine has never been able to proxy any request to any arcgis server

**Comment by bsvensson** [comment]
Closing - is fixed as part of #244

**Pull request closed without merging**
