### PR TITLE
Add "Alternatives" section

### PR DESCRIPTION
**Pull request by bsvensson**
@patrickarlt @esoekianto - can you review this new section I'm proposing?

### CODE REVIEW

**Comment by jgravois** [comment]
looks good.  i'd recommend linking to the doc on hosted service proxies [here](https://developers.arcgis.com/authentication/working-with-proxies/) too.

**Comment by bsvensson** [comment]
Thanks @jgravois - I added the link for the "Working with Proxy Services" topic on developers.arcgis.com

**Comment by esoekianto** [comment]
I like this too, I will merge this PR

**Comment by bsvensson** [comment]
Thanks @esoekianto

**Pull request merged**
