### PR TITLE
PHP: Replacing CRLF with "__" during logging

### PR DESCRIPTION
**Pull request by cheetah90**

### CODE REVIEW

**Comment by cheetah90** [comment]
Manually tested. Ran on all test cases as well.

**Comment by phpmaps** [comment]
@cheetah90 can you provide the bigger picture.  what does this class do?

**Comment by cheetah90** [comment]
Bjorn ran our proxies against Veracode code analysis. The report says the handling of CRLF in log file and in HTTP header is something we are missing and this could cause security issues. So I am sending a couple fixes for that.

**Comment by phpmaps** [comment]
You may want to try using this constant PHP_EOL.  This approach may get more cross platform even though I think we do use /n in other places.

http://php.net/manual/en/reserved.constants.php.

**Comment by cheetah90** [comment]
Thanks! I just need this kind of help from a PHP guru!

**Comment by cheetah90** [comment]
@phpmaps and I had a nice discussion on this and we agreed on keeping the current PR as it is. So ready to be merged. @bsvensson

**Pull request merged**
