### PR TITLE
Copy original HTTP request headers

### PR DESCRIPTION
**Pull request by gavinr**
* Removed conflicts from the changes from @jwoyame #186. (#175)
* Also making sure the list of headers that are in #362 are not passed along.

### CODE REVIEW

**Comment by bsvensson** [comment]
Thanks @gavinr :)

This PR has quite a few changes and potential for breaking unexpected things with the header changes.  I tested it successfully with my 26 test cases.  @MikeTschudi @jgravois et al - it'd be great and if you could also review/test.  

I plan to merge this PR if I don't hear anything the next few days...

**Comment by esoekianto** [comment]
I remember we started passing thru all header value in the past during this issue #87 , Header, "Content-Disposition". 

@bsvensson does any of your 26 test cases cover attachment scenario per issue #87 ?

If it does, we should be good.

**Comment by bsvensson** [comment]
> @bsvensson does any of your 26 test cases cover attachment scenario per issue #87

No.

**Comment by MikeTschudi** [comment]
@gavinr, some questions and comments about the DotNet flavor, please.

* In `forwardToServer()`, the older code `postBody.Length > 0?...` remains; it's commented out, but is not needed even as a comment--the new code is better.
* In `copyRequestHeaders()`, how about executing `headerKey.ToLower()` once into a local variable? Even though the compiler can handle optimizing the 11 repeats of the call, it would make the code more readable.

@bsvensson

**Comment by gavinr** [comment]
Thanks @MikeTschudi - those changes have been made. Please take a look to make sure I have completed them in alignment with what you were thinking.

**Comment by MikeTschudi** [comment]
@gavinr, thanks! 
@bsvensson, looks good to go from my perspective

**Comment by bsvensson** [comment]
Thanks  @jwoyame @gavinr @MikeTschudi

**Pull request merged**
