### PR TITLE
1.1.0 release

### PR DESCRIPTION
**Pull request by bsvensson**

### CODE REVIEW

**Comment by jgravois** [comment]
oh shoot, i just laid a commit down in the web editor for the changelog and stuck you with a merge conflict.  i'll pull this one down locally and resolve it.

**Comment by bsvensson** [comment]
ok - go ahead

**Comment by jgravois** [comment]
sorry about that.
you're going to make sure the release points at one of these commits, right?

**Comment by bsvensson** [comment]
yep :)

**Pull request merged**
