### PR TITLE
Php token expire

### PR DESCRIPTION
**Pull request by cheetah90**
Handle 10.3 server token expiration. Similar to #256

### CODE REVIEW

**Comment by bsvensson** [comment]
(a) I think it might make sense to keep this as a fallback in order to catch some wacky spacing that the other if's didn't catch.
```
$jsonData = json_decode($this->proxyBody);
$errorCode = $jsonData->{'error'}->{'code'};
```
(b) Once `$isUnauthorized` is set to true, I don't think we need to check the other if's. How about grouping them all together in one long "if", or make them if/else.

**Comment by cheetah90** [comment]
Changed per comment above. Tested against all test cases.

**Comment by bsvensson** [comment]
@cheetah90 
For a slight performance improvement - how about wrapping the last elseif in an else which includes the fallback's:
```
        $jsonData = json_decode($this->proxyBody);        
        $errorCode = $jsonData->{'error'}->{'code'};
```
Then the json_decode would only happen if not caught by the other if/elseif's, right?

**Comment by cheetah90** [comment]
Sure :)

On Mon, Aug 17, 2015 at 5:47 PM, Bjorn Svensson <notifications@github.com>
wrote:

> @cheetah90 <https://github.com/cheetah90>
> For a slight performance improvement - how about wrapping the last elseif
> in an else which includes the fallback's:
>
>         $jsonData = json_decode($this->proxyBody);
>         $errorCode = $jsonData->{'error'}->{'code'};
>
> Then the json_decode would only happen if not caught by the other
> if/elseif's, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/resource-proxy/pull/272#issuecomment-132006678>.
>



-- 
林轶伦 LIN, Yilun (Allen)

**Comment by cheetah90** [comment]
Updated per requests above and tested against all test cases.

**Comment by bsvensson** [comment]
Thank you @cheetah90 :)

**Pull request merged**
