### PR TITLE
Xsd namespace local for intellisense VS

### PR DESCRIPTION
**Pull request by nicogis**
proxy.config hasn't intellisense in VS because it isn't defined namespace

### CODE REVIEW

**Comment by jgravois** [comment]
looking at the [diff](https://github.com/Esri/resource-proxy/pull/484/files), it looks like you've addressed #481, #482 (and #483?) all at once, correct?

**Comment by nicogis** [comment]
#481 and #482
I haven't added #483 because peraphs maybe it's better write in proxy a message for special symbol ('&' '< '>' ect) in user and /or password and escape char '\' .

**Comment by jgravois** [comment]
its usually a good rule of thumb to isolate each individual unrelated proposed fix in its own branch so that you can discuss the work with maintainers and make changes independently.

what you have here already isn't too overwhelming though, and we appreciate you jumping in and opening up a pull request with your suggestions!

**Comment by nicogis** [comment]
Ok.

**Pull request closed without merging**
