### PR TITLE
Support subdomain wildcards #30

### PR DESCRIPTION
**Pull request by guo7711**
Support subdomain wildcards #30 - Same logic as #122

### CODE REVIEW

**Comment by jgravois** [comment]
:+1:

**Comment by cheetah90** [comment]
Cannot verify this PR. Used the following config in proxy.config 
`<serverUrl url="https://*.arcgis.com" matchAll="true"/>` 
and tried to get access to `https://developers.arcgis.com/javascript/` got `{error: {code: 403,message:"Proxy has not been set up for this URL. Make sure there is a serverUrl in the configuration file that matches: https://developers.arcgis.com/javascript/ https://developers.arcgis.com/javascript/"}}` 

Actually, the base of this PR isn't the current master branch. Can you merge the current master branch to your branch first? Thanks!

**Comment by jgravois** [comment]
@guo7711 let me know if you need any help merging the latest commits in Esri/master into your feature branch so that @cheetah90 can retest.

**Comment by guo7711** [comment]
@cheetah90 Would you please test #215 instead and close this pull request? #215 is a improved version of this one and handles more situation.

**Comment by bsvensson** [comment]
Closing this PR as it's been replaced by a newer, improved pull request - #215.

**Pull request closed without merging**
