### PR TITLE
DotNet: split query string and uri for POST request

### LINKED ISSUE #177: Support for ArcGIS Server 10.3
DotNet and Java Proxy failed to get token to ArcGIS Server 10.3 with this error in the log file, 

```
WARNING: Token cannot be obtained: {"error":{"code":405,"message":"Method not supported","details":"Generate Token request should not contain username and password in the query string."}}
```

This is because ArcGIS Server 10.3 only supports POST request for token request and does not support username and password in query string , see this doc, http://server.arcgis.com/en/server/latest/administer/windows/acquiring-arcgis-tokens.htm

### PR DESCRIPTION
**Pull request by esoekianto**
split the query string from uri for POST request, to support token request for server 10.3

should fix #177

### CODE REVIEW

**Comment by jgravois** [comment]
@bsvensson can you review/merge and follow up with a PHP fix too?  

i just got another customer inquiry about this....

**Comment by phpmaps** [comment]
Is there a repro case?  What's wrong with the PHP proxy? 

I am pretty sure the PHP proxy uses built-in PHP methods to identify a query string.

**Comment by hgonzago** [comment]
@phpmaps The problem is that when trying to proxy attachments, it never works when using the PHP version. Same exact JS code and secured feature service with attachments proxies correctly if done via the ASP.Net version.

This problem initially was logged a couple months back. Initially, you couldn't proxy any attachments, regardless of the proxy version used. We now enabled attachment proxying with the API but it still fails but only when using PHP (haven't tried it with JSP so can't speak to that.)

Thanks:-)

cc: @bsvensson

**Comment by bsvensson** [comment]
@hgonzago - the issue about proxying attachment using the PHP proxy is a different problem - #221

**Pull request merged**
