### PR TITLE
add cors headers + update xml headers

### PR DESCRIPTION
**Pull request by kubaszostak**
- enable cross-origin resource sharing regarding to http://enable-cors.org
- enable access to OGC:WMS Services provided by non-esri software by changing  application/vnd.ogc.wms_xml' header to 'application/xml'

### CODE REVIEW

**Comment by bsvensson** [comment]
Thanks @kubaszostak,
Do you have some good example (public) WMS sites that works with this fix (and fails without it)? Or anything else that would make it easy for us to test this pull request?

**Comment by kubaszostak** [comment]
_Content-Type: application/vnd.ogc.wms_xml_

I belive all http://geoserver.org WMS Services are published with `Content-Type: application/vnd.ogc.wms_xml` header. Examples from Europe:
http://wms.gdos.gov.pl/geoserver/wms? 
http://openwms.statkart.no/skwms1/wms.topo2?
http://129.206.228.72/cached/osm/service?
http://watzmann.geog.uni-heidelberg.de/cached/osm?

If you have java proxy this services will not work with ESRI JavaScript API. It seems to me like JavaScript code cuts down unknowns Content-Type respones. It would be better to change JavaScript code but there is no source code on github. So to fix this I propose to change any "*XML"  Content-Type header response to "application/xml". In fact this what yours http://developers.arcgis.com/proxy/ is already doing. If you check response headers for http://wms.gdos.gov.pl/geoserver/wms?Request=GetCapabilities you will see `Content-Type: application/vnd.ogc.wms_xml`. But if you get the same via yours proxy http://developers.arcgis.com/proxy/?http://wms.gdos.gov.pl/geoserver/wms?Request=GetCapabilities you will see `Content-Type: text/xml`. 

To check esri's response headers go to
http://developers.arcgis.com/javascript/sandbox/sandbox.html?sample=layers_wms
and put somewere in script section this code:
```javascript
      require( ["dojo/request/xhr"],
        function(request, dom){
      
          var url = "http://developers.arcgis.com/proxy/?http://wms.gdos.gov.pl/geoserver/wms?Request=GetCapabilities";
          var promise = request.get(url);

          promise.response.then(function(response) {
              console.log("status", response.status);
              console.log("url", response.url);
              console.log("header", response.getHeader('Content-Type'));
              console.log("data", response.data.substring(1, 400));
          });
        }
      );
```
---
_Access-Control-Allow-Origin_

Non-local request can be allowed via config `allowedReferers` property. But if there is no `Access-Control-Allow-Origin` header browser will deny such requests.

---

ps.
To compare old one with new one you can use code with my changes served at
http://proxy-ksz.rhcloud.com/proxy.jsp

**Comment by cheetah90** [comment]
Hi @kubaszostak, thanks for submitting this PR. I could reproduce your issue but I cannot verify your fix. After applying your fix, and sending request to http://wms.gdos.gov.pl/geoserver/wms?Request=GetCapabilities I got the following error. 

```
HTTP Status 500 - An exception occurred processing JSP page /proxy.jsp at line 158

type Exception report

message An exception occurred processing JSP page /proxy.jsp at line 158

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: An exception occurred processing JSP page /proxy.jsp at line 158

155:     while (headerNames.hasMoreElements()) {
156:         String key = (String) headerNames.nextElement();
157:         String value = request.getHeader(key);
158:         if (!key.equalsIgnoreCase("host")) con.setRequestProperty(key, value);
159:     }
160:     return true;
161: }


Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:574)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:471)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

java.lang.IllegalStateException: Already connected
	sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(HttpURLConnection.java:3013)
	org.apache.jsp.proxy_jsp.passHeadersInfo(proxy_jsp.java:163)
	org.apache.jsp.proxy_jsp._jspService(proxy_jsp.java:944)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.24 logs.

Apache Tomcat/8.0.24
```

**Comment by bsvensson** [comment]
I tested the latest version of the DotNet, PHP and JSP proxies, and all of them parse along the 
`Content-Type: application/vnd.ogc.wms_xml` from http://wms.gdos.gov.pl/geoserver/wms?Request=GetCapabilities.  Note that the proxy used on the developers.arcgis.com site is not the same code as the proxy in this repo.  

The proxy shouldn't have to hard-code the content-type.

As for CORS, it seems better to set it up on the web server where the proxy is running (as opposed to hard-code it into the proxy).

I'm closing this pull request, but feel free to comment/reopen with more info.

**Pull request closed without merging**
