### PR TITLE
Java: split query string and uri for POST request

### LINKED ISSUE #177: Support for ArcGIS Server 10.3
DotNet and Java Proxy failed to get token to ArcGIS Server 10.3 with this error in the log file, 

```
WARNING: Token cannot be obtained: {"error":{"code":405,"message":"Method not supported","details":"Generate Token request should not contain username and password in the query string."}}
```

This is because ArcGIS Server 10.3 only supports POST request for token request and does not support username and password in query string , see this doc, http://server.arcgis.com/en/server/latest/administer/windows/acquiring-arcgis-tokens.htm

### PR DESCRIPTION
**Pull request by esoekianto**
split the query string from uri for POST request, to support token request for server 10.3 

should fix #177

### CODE REVIEW

**Comment by jgravois** [comment]
@Esri/oauth2-proxy can you folks in tech support manually test this PR (and #179) to make sure they don't introduce anything unexpected and merge please?

**Comment by cheetah90** [comment]
Cannot verify. (Applied on the top of #212 ) this fix will break the AGOL login. Test case: try this link http://alin:8080/Java/proxy.jsp?https://logistics.arcgis.com/arcgis/rest/services/World?f=pjson

**Comment by bsvensson** [comment]
@esoekianto - can you update this conflicted pull request?  
Thanks :)

**Comment by esoekianto** [comment]
@bsvensson see #179

**Comment by bsvensson** [comment]
@esoekianto - I assume you mean #238 :)

**Pull request closed without merging**
