### PR TITLE
DotNet: Support more format for allowed referer #166

### LINKED ISSUE #166: JSP: allowed referer value can only work with this format "sub.domain.com"
it should be able to accept these format,

"sub.domain.com" - accept both http and https
"sub.domain.com/folder" - accept both http and https
"http://sub.domain.com" - accept only http
"https://sub.domain.com/folder" - accept only https
"//sub.domain.com" - accept both http and https

### PR DESCRIPTION
**Pull request by guo7711**
Fixed #166 in DotNet

"sub.domain.com" - accept both http and https
"sub.domain.com/folder" - accept both http and https
"http://sub.domain.com" - accept only http
"https://sub.domain.com/folder" - accept only https
"//sub.domain.com" - accept both http and https
"*.domian.com" - accept both http, https, all the subdomains and folders.

### CODE REVIEW

**Comment by jgravois** [comment]
:+1:

**Comment by afili** [comment]
Good job @guo7711 !!

One question: This implementation does not check for referer prefix but it checks if the proxy's referer is equal with the application's referer 
(if (referer.ToLower().Equals(allowedRefererAccepted.ToLower())) return true;)

So for example if I have allowedReferers="http://artemisfl.esri.com" and the app uses http://artemisfl.esri.com/app.html, this will not pass. Should we allow any referer that starts with a prefix? If yes then we may have to use method ProxyConfig.isUrlPrefixMatch. If not then checking for equality is fine.

Other than that I tested 
"sub.domain.com" 
"http://sub.domain.com"
"//sub.domain.com"
"*.domian.com"

and all worked as expected! I haven't tested the folders yet.

**Comment by guo7711** [comment]
In fact, besides checking if the proxy's referer is equal with the application's referer, it will also check folder and subdomain, equal is just one of the conditions returns true. I don't think we should allow any referer starts with a prefix, because if allowedReferer="sub.domain.com/folder", we don't want to pass "sub.domain.com/folders".

You are right, if I have allowedReferers="http://artemisfl.esri.com" and the app uses "http://artemisfl.esri.com/app.html", this will not pass. The reason is we split the allowed referer parts by ".", if the app uses "http://artemisfl.esri.com/app", it will pass. We will see how we can improve from here. @esoekianto

**Comment by cheetah90** [comment]
@guo7711 In your first post, when you say "sub.domain.com" - accept both http and https

I guess you mean "//sub.domain.com"? Do I understand correctly?

**Comment by guo7711** [comment]
"sub.domain.com" means "sub.domain.com" without any slash and protocol names.
What's your test case on double-slashes and wildcard?

**Comment by cheetah90** [comment]
In the proxy.config, I have `<serverUrl url="developers.arcgis.com" matchAll="true"/>` and the request I made is `http://alin.esri.com/DotNet/proxy.ashx?http://developers.arcgis.com`

**Comment by esoekianto** [comment]
@cheetah90 we are talking about referer here, for allowedReferer

**Comment by cheetah90** [comment]
Oh my bad!!! Stupid mistake! Sorry about that :)

**Comment by cheetah90** [comment]
Tested and verified! @bsvensson @guo7711 !

**Comment by guo7711** [comment]
Thanks for testing @cheetah90

**Comment by cheetah90** [comment]
I want to re-open the discussions about, if we have `allowedReferers="http://artemisfl.esri.com"` in proxy.config, should we allow `Referer="http://artemisfl.esri.com/app.html". If there is needs for this, I will implement this rule in JSP, which I am currently working on and patch it on DotNet and PHP. 

Any suggestions?

**Comment by jgravois** [comment]
@cheetah90 i agree with @afili's earlier comment that we should allow any url that starts with the same prefix

**Comment by guo7711** [comment]
@cheetah90 I agree. We should allow subfolders and files. Same prefix may cause that when allowedReferer="sub.domain.com/folder", "sub.domain.com/folders" will get through. We might need to set up a new rule on it. @jgravois

**Comment by cheetah90** [comment]
After discussion with @bsvensson, we decided to add the support for ending wildcard to make it absolutely clear. 
So sub.domain.com/folder/* will support sub.domain.com/folder/app.html and sub.domain.com/app.html
while
sub.domain.com/folder will just do exact match. 

I've written up a reference for the [rules for allowedReferer](https://devtopia.esri.com/bjor3345/resource-proxy-testing/wiki/Testing-for-allowedReferer)  Please send me/Bjorn comments and suggestions! After we finalized the rules, the plan is to conform to the ServerUrl.

**Comment by jgravois** [comment]
> ... and sub.domain.com/app.html

i think you mean 'sub.domain.com/**folder**/app.html

also, no use linking to devtopia docs.  not all of us have access :smile:

**Pull request merged**
