### PR TITLE
Add logLevel support in proxy.config #127

### PR DESCRIPTION
**Pull request by guo7711**
Support logLevel setting in proxy.config as follows:
<ProxyConfig allowedReferers="*"
             mustMatch="true"
             logFile="D:\log.txt"
             logLevel="Info">
logLevel can be set as "Off","Error","Warning","Info","Verbose" or 0-4. This setting only effects logFile in proxy.config.
Logfile in web.config will remain the same.
The default value for logLevel is "Error".

### CODE REVIEW

**Comment by bsvensson** [comment]
@afili - could you review and test this pull request?

**Comment by afili** [comment]
thanks @guo7711 for submitting this pull request. Can you also provide some sample cases just to make sure that my understanding is correct? Is off < error < warning < info < verbose? For example if I have logLevel="Error or logLevel="Warning" in my proxy.config, I should not see the log message for the ping which is Info level, is this correct?

**Comment by guo7711** [comment]
@afili Yes that is correct. The logLevel is defined as follows. A higher logLevel setting will display all logs lower and equal to that level.

Off	        0	None
Error	1	Only error messages
Warning	2	Warning messages and error messages
Info	        3	Informational messages, warning messages, and error messages
Verbose	4	Verbose messages, informational messages, warning messages, and error messages

**Comment by guo7711** [comment]
@afili @bsvensson Sorry I messed up my local git so I will close this pull request. I made some changes and submitted a new pull request at https://github.com/Esri/resource-proxy/pull/234

**Pull request closed without merging**
