### PR TITLE
Fix the "Already Connect"

### PR DESCRIPTION
**Pull request by cheetah90**
Fixed the "Already Connect" Issue #182. Refactor the PR #235 to reduce function overload of doHTTPRequest()

### CODE REVIEW

**Comment by cheetah90** [comment]
Test the fix against all existing JSP test cases and work well :)

**Comment by cheetah90** [comment]
cc: @bsvensson

**Comment by bsvensson** [comment]
@cheetah90 - There seem to be some un-intended changes with whitespace, and the .gitignore. Can you clean that up?

**Comment by cheetah90** [comment]
Revert to the original indentation. If you agree, I will fix the inconsistent indentation to having all of them 2 spaces. Sounds good?

**Pull request merged**
