### PR TITLE
Pass back full response, fixes #190

### LINKED ISSUE #190: PHP proxy fails to pass back full response
This came about when trying to use the most recent PHP proxy against the basic directions Javascript sample. Swapping out the proxy file with the PHP one on my machine (OSX Mavericks, and then Yosemite) and adding my credentials to the config file. When running the same everytime i would get an "Undefined token error" and after checking the response back from the route service via the proxy, it was always truncated, "dojo.io.script.jsonp_dojoIoScript1._jsonpCallback({"currentVersion":10.3,"layerName":"Route_World","layerType":"esriNAServerRouteLayer","impedance":"TravelTime","restrictions":["Avoid Unpaved Roads","Avoid "

Notice that the full JSON callback is cut off. To narrow down if it was machine specific, I configured a clean Apache instance on my personal Macbook running Yosemite (older hardware model, via 2012) and got the same exact error message when trying to run this sample.

Spoke to @phpmaps and he had an idea what was going on. Created this issue so that the fix he implemented in an updated PHP could be merged into this repo.

### PR DESCRIPTION
**Pull request by phpmaps**
Bit of header rework in this pull request.  Made sure that the proxy captures the incoming request headers from the client and uses them when making the cURL request.  

Next the PHP proxy reads the cURL response and collects all the headers.  These headers are then sent to the client along with the response.  

Occasionally folks were seeing the full response was not getting sent, aka a truncated response.  This was b/ the Content-Length property was incorrect.  The proxy now calculates Content-Length and sets the proper Content-Length property.

### CODE REVIEW

**Comment by jgravois** [comment]
i think you ended up with some unintended stuff in this Pull Request (ie: line 201 of proxy-verification.php and the overwritten proxy.config).

let me know if you need a hand squashing/rebasing.  the alternative would be to lay down the same changes in a single commit in a new feature branch.

**Comment by phpmaps** [comment]
Very, likely john.  I believe the proxy.php file is correct.  If you are using the PHP version would you swap it out for this proxy.php file?  Let's try and connect this week.

**Comment by phpmaps** [comment]
@hgonzago  Hi Heather - The proposed fix is in. It's in the proxy.php file.  I will work with John on cleaning up the Git part.

**Comment by jgravois** [comment]
closing in favor of #193

**Pull request closed without merging**
