### PR TITLE
Serverurl empty error

### PR DESCRIPTION
**Pull request by guo7711**
Add mustMatch check logic in GetConfigServerUrl(string uri).
Add constructors in ServerUrl class.

### CODE REVIEW

**Comment by esoekianto** [comment]
working with @guo7711 to make few tweeks

**Comment by jgravois** [comment]
nothing wrong with leaving a PR open and laying down more commits to get things perfect prior to merging, but either way... :smile:

**Comment by guo7711** [comment]
@esoekianto #297 is the updated PR.

**Comment by jgravois** [comment]
@guo7711 and @esoekianto thank you both for your quick fix!

**Pull request closed without merging**
